"use client";
import { useEffect,useRef,useState } from "react";
import { ProductModal } from "@/components/cliente/product-modal"; import { Back } from "@/components/shared/back"; import { CartBar } from "@/components/shared/cart-bar"; import { ProductImage } from "@/components/shared/product-image"; import { Shell } from "@/components/shared/shell"; import { useCart } from "@/hooks/use-cart"; import { useMenuItems } from "@/hooks/use-menu-items"; import { formatPrice,toNumber } from "@/lib/formatters"; import type { Dish } from "@/types/menu";
export function Menu(){
 const [locale,setLocale]=useState<"pt"|"en"|"es">("pt"); const {items,loading,error}=useMenuItems(false,locale); const {cart,add,totalItems}=useCart(); const [active,setActive]=useState("Todos"); const [selected,setSelected]=useState<Dish|null>(null); const scroller=useRef<HTMLDivElement>(null);
 useEffect(()=>{const saved=localStorage.getItem("ditus-language");setLocale(saved==="EN"?"en":saved==="ES"?"es":"pt");},[]);
 const available=items.filter(i=>i.active),categories=[...new Set(available.map(i=>i.category))],visible=active==="Todos"?available:available.filter(i=>i.category===active),total=cart.reduce((s,c)=>s+toNumber(items.find(i=>i.id===c.dishId)?.price??"R$ 0")*c.quantity,0);
 const scroll=(direction:number)=>scroller.current?.scrollBy({left:direction*180,behavior:"smooth"});
 return <Shell><header className="menu-header"><Back href="/cliente"/><div><h1>Cardápio</h1><p>Restaurante Ditus</p></div><a href="/cliente/carrinho" className="bag" aria-label={`Ver carrinho, ${totalItems} itens`}>🛒<b>{totalItems}</b></a></header><section className="menu"><div className="category-nav"><button aria-label="Categorias anteriores" onClick={()=>scroll(-1)}>‹</button><div className="chips" ref={scroller}><button className={active==="Todos"?"selected":""} onClick={()=>setActive("Todos")}>Todos</button>{categories.map(c=><button key={c} className={active===c?"selected":""} onClick={()=>setActive(c)}>{c}</button>)}</div><button aria-label="Próximas categorias" onClick={()=>scroll(1)}>›</button></div><h2>{active==="Todos"?"Mais pedidos":active}</h2>{loading&&<p className="empty-menu">Carregando cardápio...</p>}{error&&<p className="feedback-message error">{error}</p>}{visible.map(item=><article className="dish" key={item.id} onClick={()=>setSelected(item)}><ProductImage src={item.imageUrl} alt={item.name} fallback={item.emoji}/><div><h3>{item.name}</h3><p>{item.description}</p><b>{item.price}</b></div><button aria-label={`Adicionar ${item.name} ao carrinho`} onClick={(event)=>{event.stopPropagation();add(item.id)}}>+</button></article>)}</section>{totalItems>0&&<CartBar total={formatPrice(total)}/>} {selected&&<ProductModal dish={selected} onClose={()=>setSelected(null)} onAdd={()=>{add(selected.id);setSelected(null)}}/>}</Shell>;
}
